### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by luisfmelo** [victoriadrake/hydra-link-checker#1]
I tried your code but it seems that it is failing due to SSL issues.
I tried a few of my sites as well as your personal blog: https://victoria.dev

**Comment by victoriadrake** [comment]
Thanks for raising this Luís. Can you share some error output to help me better understand what you mean by “SSL issues”?

**Comment by luisfmelo** [comment]
I figured it out. I needed to install python certificates in MacOS.
Nevertheless, I'm having some "issues" that can be, potentially, improvements.

- You are saying that a `mailto:` link is a failure. It may appear in the top of the report as a counter but I think it should not appear as a failure.
- Some links the report said they are broken but I think that it was some request limiter problem. We could improve the code to try in a few seconds.
- Some links will redirect to authenticated pages. They should not be added as failures, instead, it should be a counter.

This is just my opinion. Maybe you have different interpretations. Let me know what you think.
If you want, I can try to help you with some features. It would be nice if you start some kind of **github project** or using **issues** to let people know the roadmap you are idealizing. (if you want to improve and continue to work on this project of course)

**Comment by victoriadrake** [comment]
I'm glad you got it figured out!

The timeouts can be adjusted; this may help with the request limiting. The relevant lines are `42` and `175`. Some amount of tuning is probably warranted to better suit your system, and the site you want to check. Other than that, there's no proper implementation yet for dealing with rate limiting.

I agree about the `mailto:` links! Would you be up for submitting a PR addressing this?

How would you imagine implementing the counter for authenticated pages?

Thank you for your feedback, Luís!

**Comment by victoriadrake** [comment]
Closed in #2.
