### ISSUE TITLE
Returning exit code 1 when there are broken links present leads to failed runs in GitHub Actions. Make it optional to return exit code 1

### ISSUE THREAD

**Issue by tushar5526** [victoriadrake/hydra-link-checker#15]
**Is your feature request related to a problem? Please describe.**
It is failing the GHA workflows.

**Describe the solution you'd like**
Returning exit code 1 should be optional.

**Comment by tushar5526** [comment]
Also, ideally, the script is should fail when there is some error in the script, not when the website has broken links.

**Comment by victoriadrake** [comment]
I'd be open to a PR for this feature. In the meantime, depending on what you want to accomplish, you may be able to use [status check functions](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions) to conditionally run your desired behavior.

**Comment by tushar5526** [comment]
Sure. I will be glad to do it. Please assign this to me :)

**Comment by tushar5526** [comment]
> I'd be open to a PR for this feature. In the meantime, depending on what you want to accomplish, you may be able to use [status check functions](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions) to conditionally run your desired behaviour.

Status check is what we are using right now, but the workflow is still tagged as *failed* even though we are able to execute all our jobs. Due to the failed workflow, our GHA status badge present on the home README.md has a failing tag.
