### ISSUE TITLE
Exclude tel: links

### ISSUE THREAD

**Issue by szieglerICF** [victoriadrake/hydra-link-checker#5]
**Describe the bug**
tel: links are reported as bad links and should just be excluded from checks.

**To Reproduce**
1. Run the script on a site that includes telephone links

**Expected behavior**
tel: links are reported as bad but should just be skipped

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: MacOS

**Smartphone (please complete the following information):**
NA

I've got a fix and will fork and submit a PR

**Comment by victoriadrake** [comment]
Thank you!

**Comment by victoriadrake** [comment]
Closed in #6
