### ISSUE TITLE
Add the ability to use a configuration file

### ISSUE THREAD

**Issue by victoriadrake** [victoriadrake/hydra-link-checker#8]
**Is your feature request related to a problem? Please describe.**
Hydra has a number of configurable variables. It would be nice to be able to use an external file to set these.

**Describe the solution you'd like**
An external file can set configuration variables for hydra's constants, like `TAGS`, `EXCLUDE_SCHEME_PREFIXES`, `THREADS`, `TIMEOUT`, and `OK`.

**Comment by stevezieglerva** [comment]
Hi, I think this would be nice also. I was going to request this feature but thought it might go against your current clean, lightweight design. 

I could probably help with this. Would TOML work?

**Comment by stevezieglerva** [comment]
I also wanted to have an option to skip LinkedIn links which typically return a 999 for some crazy reason.

**Comment by victoriadrake** [comment]
That would be awesome! 🙌

**Comment by stevezieglerva** [comment]
Hi, I submitted a PR. Have you had a chance to look at it?

**Comment by victoriadrake** [comment]
Not yet, Steve! I want to make sure I afford it the brainpower it deserves 😁

**Comment by stevezieglerva** [comment]
Sounds good.

**Comment by victoriadrake** [comment]
This was closed by #9.
